Add PIDFILE logic

diff --git a/roles/aws.ebs_scale/templates/ebs_autoscale.sh.j2 b/roles/aws.ebs_scale/templates/ebs_autoscale.sh.j2
--- a/roles/aws.ebs_scale/templates/ebs_autoscale.sh.j2
+++ b/roles/aws.ebs_scale/templates/ebs_autoscale.sh.j2
@@ -42,6 +42,32 @@
 #
 #Print all the things.
 #set -x
+PIDFILE=/var/run/ebs_autoscale.pid
+if [ -f $PIDFILE ]
+then
+  PID=$(cat $PIDFILE)
+  ps -p $PID > /dev/null 2>&1
+  if [ $? -eq 0 ]
+  then
+    echo "Process already running"
+    exit 1
+  else
+    ## Process not found assume not running
+    echo $$ > $PIDFILE
+    if [ $? -ne 0 ]
+    then
+      echo "Could not create PID file"
+      exit 1
+    fi
+  fi
+else
+  echo $$ > $PIDFILE
+  if [ $? -ne 0 ]
+  then
+    echo "Could not create PID file"
+    exit 1
+  fi
+fi
 
 # Base name for VG and LV.
 # VG = vg_$NAME
@@ -158,6 +184,7 @@ check_if_mounted(){
     else
         log "${MOUNT_POINT} not mounted. Go panic."
         send_msg "${MOUNT_POINT} not mounted. Panic at the disco."
+        rm $PIDFILE
         exit 1
     fi
 }
